branch-defaults:
  default:
    environment: MediumArticle-Users-env
environment-defaults:
  MediumArticle-Users-env:
    branch: null
    repository: null
global:
  application_name: Medium Article
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Node.js 12 running
    on 64bit Amazon Linux 2/5.0.2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
